"use client";

/**
 * The people who take calls.
 *
 * An agent is a person with an extension: a row in `agent_extensions`, which
 * Asterisk reads through the bridge over `res_config_curl`. Adding one here is
 * the whole of provisioning — no config file, no `pjsip reload` — which is the
 * reason the schema was built that way.
 *
 * ## The password is generated, shown once, and never listed
 *
 * SIP digest authentication needs the plaintext to compute a response, so it
 * cannot be hashed the way a login password is. That makes it a credential
 * rather than a field: **no route returns it** — the resource's column list
 * leaves it out, and the control plane honours that list on the detail and the
 * write as well as the list, which it did not until this screen was built. The
 * only time it exists in a browser is the moment it is generated here, so it is
 * shown once. If somebody loses it, the answer is a new one, not a way to look
 * the old one up.
 */

import { useState } from "react";

import { Button } from "@/components/base/buttons/button";
import { Dialog, Modal, ModalOverlay } from "@/components/application/modals/modal";
import { Input } from "@/components/base/input/input";
import { ResourceListScreen } from "@/components/application/screens/resource-list-screen";
import { SipCredentials } from "@/components/application/screens/sip-credentials";
import { api } from "@/utils/api-client";
import { generateSipPassword } from "@/utils/sip-password";
import { useSession } from "@/hooks/use-session";

export const TeamScreen = () => {
    const [open, setOpen] = useState(false);

    return (
        <>
            <ResourceListScreen
                resourceKey="agent-extensions"
                createSlot={
                    <Button size="sm" onClick={() => setOpen(true)}>
                        Add Agent
                    </Button>
                }
            />
            <AddAgentDialog isOpen={open} onClose={() => setOpen(false)} />
        </>
    );
};

const AddAgentDialog = ({ isOpen, onClose }: { isOpen: boolean; onClose: () => void }) => {
    const { context } = useSession();

    const [name, setName] = useState("");
    const [extension, setExtension] = useState("");
    const [saving, setSaving] = useState(false);
    const [error, setError] = useState<string | null>(null);
    /** Set once the agent exists. The only time this password is ever shown. */
    const [created, setCreated] = useState<{ endpoint: string; password: string } | null>(null);

    const valid = /^[0-9]{3,6}$/.test(extension) && name.trim().length > 0;

    const create = async () => {
        if (!context || !valid) return;
        setSaving(true);
        setError(null);
        const password = generateSipPassword();
        try {
            const { data } = await api.create<{ endpoint: string }>(
                "agent-extensions",
                {
                    org_id: context.organizationId,
                    display_name: name.trim(),
                    extension: extension.trim(),
                    sip_password: password,
                    status: "active",
                },
                context,
            );
            // `endpoint` is generated by the database from the org's slug, so
            // it is read back rather than guessed — the app must show the name
            // Asterisk will actually know, not one composed here.
            setCreated({ endpoint: data?.endpoint ?? "", password });
        } catch (e) {
            setError(e instanceof Error ? e.message : "Could not add the agent");
        } finally {
            setSaving(false);
        }
    };

    const finish = () => {
        setCreated(null);
        setName("");
        setExtension("");
        setError(null);
        onClose();
        // The list is a separate fetch; a reload is blunt but honest, and this
        // happens once per person hired.
        window.location.reload();
    };

    return (
        <ModalOverlay isOpen={isOpen} onOpenChange={(v) => (v ? undefined : created ? finish() : onClose())}>
            <Modal className="max-w-lg">
                <Dialog>
                    {/* The card is this inner div, not the Dialog. Styling the
                        Dialog itself gives a panel with no width and no ground,
                        which reads as a broken screen rather than a dialog. */}
                    <div className="flex w-full flex-col rounded-xl bg-primary p-6 shadow-xl ring-1 ring-secondary">
                    {created ? (
                        <>
                            <h2 className="text-lg font-semibold text-primary">Agent added</h2>
                            <p className="mt-1 text-sm text-tertiary">
                                These are the only credentials this agent needs. The password is shown
                                now and cannot be shown again — SIP authentication needs it in plain
                                text, so it is not stored in a form anything can read back.
                            </p>

                            <SipCredentials endpoint={created.endpoint} password={created.password} />

                            <div className="mt-6 flex justify-end">
                                <Button size="sm" onClick={finish}>
                                    Done
                                </Button>
                            </div>
                        </>
                    ) : (
                        <>
                            <h2 className="text-lg font-semibold text-primary">Add an agent</h2>
                            <p className="mt-1 text-sm text-tertiary">
                                Somebody who can take a call the AI hands over.
                            </p>

                            <div className="mt-5 flex flex-col gap-4">
                                <Input
                                    label="Name"
                                    placeholder="Priya Nair"
                                    value={name}
                                    onChange={setName}
                                    isRequired
                                />
                                <Input
                                    label="Extension"
                                    placeholder="4002"
                                    value={extension}
                                    onChange={setExtension}
                                    isRequired
                                    hint={
                                        extension && !/^[0-9]{3,6}$/.test(extension)
                                            ? "Three to six digits."
                                            : "What a colleague would say out loud. Three to six digits, unique in your organisation."
                                    }
                                    isInvalid={Boolean(extension) && !/^[0-9]{3,6}$/.test(extension)}
                                />
                            </div>

                            {error && <p className="mt-4 text-sm text-error-primary">{error}</p>}

                            <div className="mt-6 flex justify-end gap-3">
                                <Button size="sm" color="secondary" onClick={onClose}>
                                    Cancel
                                </Button>
                                <Button size="sm" isDisabled={!valid} isLoading={saving} onClick={create}>
                                    Add agent
                                </Button>
                            </div>
                        </>
                    )}
                    </div>
                </Dialog>
            </Modal>
        </ModalOverlay>
    );
};
