//! Asterisk asks the bridge what its agents are.
//!
//! This is PJSIP Realtime, with the bridge as the backend instead of a
//! database driver. Asterisk has neither `res_config_pgsql` nor
//! `res_config_odbc` — only curl, ldap and sqlite3 — and the Supabase container
//! publishes no port on the host, so there is nothing for a driver to connect
//! to. `res_config_curl` fits exactly: Asterisk POSTs, the bridge answers from
//! the database it already reads.
//!
//! Provisioning an agent therefore stays what it should be — a row in
//! `agent_extensions` — with no config file to write and no `pjsip reload`.
//!
//! ## The contract, from Asterisk's own documentation
//!
//! ```text
//! POST <base>/single   id=sarvathra-4001
//!   -> id=sarvathra-4001&transport=transport-wss&webrtc=yes…
//!
//! POST <base>/multi    id%20LIKE=%25
//!   -> one URL-encoded line per object
//! ```
//!
//! Percent-encoded `key=value` pairs, `&`-separated, one line per object, and
//! `200` even when nothing matched — an empty body is "no such endpoint", which
//! is a normal answer rather than an error.
//!
//! ## Multitenancy
//!
//! Asterisk has no tenant concept, so the endpoint *name* carries the org:
//! `<org slug>-<extension>`, generated by the database rather than typed. Two
//! clinics can both have a 4001 and never collide. Isolation of *calls* is not
//! done here at all — the switch decides which agents a call may reach, because
//! it is the thing that already knows which org the call belongs to.

use std::collections::BTreeMap;

use serde_json::Value;

/// Where PJSIP looks things up.
///
/// Only these three are served. **Contacts are deliberately absent**: they are
/// written by Asterisk on every registration, so serving them would mean
/// implementing store, update and destroy, and holding a registration's
/// lifetime in a database that has no reason to care. Left unmapped, Asterisk
/// keeps contacts in memory, which is where a thing that expires in five
/// minutes belongs.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Family {
    Endpoint,
    Auth,
    Aor,
}

impl Family {
    pub fn parse(name: &str) -> Option<Self> {
        match name {
            "ps_endpoints" => Some(Self::Endpoint),
            "ps_auths" => Some(Self::Auth),
            "ps_aors" => Some(Self::Aor),
            _ => None,
        }
    }
}

/// One agent, as the database holds it.
#[derive(Debug, Clone)]
pub struct Agent {
    pub endpoint: String,
    pub sip_password: String,
    pub display_name: String,
    pub extension: String,
}

impl Agent {
    pub fn from_row(row: &Value) -> Option<Self> {
        let get = |k: &str| row.get(k).and_then(Value::as_str).unwrap_or_default().to_string();
        let endpoint = get("endpoint");
        if endpoint.is_empty() {
            return None;
        }
        Some(Self {
            sip_password: get("sip_password"),
            display_name: get("display_name"),
            extension: get("extension"),
            endpoint,
        })
    }
}

/// Percent-encode a value for the response body.
///
/// Asterisk parses the answer as a query string, so a display name with a space
/// or an ampersand in it would otherwise split one field into two — and the
/// endpoint would come back subtly wrong rather than missing, which is worse.
fn encode(value: &str) -> String {
    let mut out = String::with_capacity(value.len());
    for byte in value.bytes() {
        match byte {
            b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'-' | b'_' | b'.' | b'~' => {
                out.push(byte as char)
            }
            other => out.push_str(&format!("%{other:02X}")),
        }
    }
    out
}

fn line(fields: &BTreeMap<&str, String>) -> String {
    fields
        .iter()
        .map(|(k, v)| format!("{k}={}", encode(v)))
        .collect::<Vec<_>>()
        .join("&")
}

/// One agent rendered for one family.
///
/// The columns are PJSIP's own, not ours: Asterisk validates them against the
/// same schema `pjsip.conf` uses, so an unknown key is refused and a missing
/// required one leaves the endpoint unusable with nothing said about why.
pub fn render(agent: &Agent, family: Family) -> String {
    let mut f: BTreeMap<&str, String> = BTreeMap::new();
    match family {
        Family::Endpoint => {
            f.insert("id", agent.endpoint.clone());
            f.insert("transport", "transport-wss".into());
            f.insert("aors", agent.endpoint.clone());
            f.insert("auth", agent.endpoint.clone());
            f.insert("context", "agents".into());
            f.insert("disallow", "all".into());
            f.insert("allow", "opus".into());
            // Asterisk's own shorthand for the whole WebRTC set — ICE,
            // DTLS-SRTP, rtcp_mux, AVPF. Spelling those out here would be a
            // second definition of "WebRTC" able to drift from Asterisk's.
            f.insert("webrtc", "yes".into());
            f.insert("trust_id_inbound", "yes".into());
            f.insert(
                "callerid",
                if agent.display_name.is_empty() {
                    format!("Agent <{}>", agent.extension)
                } else {
                    format!("{} <{}>", agent.display_name, agent.extension)
                },
            );
        }
        Family::Auth => {
            f.insert("id", agent.endpoint.clone());
            f.insert("auth_type", "userpass".into());
            f.insert("username", agent.endpoint.clone());
            f.insert("password", agent.sip_password.clone());
        }
        Family::Aor => {
            f.insert("id", agent.endpoint.clone());
            // One contact, and the newest wins. A laptop that was closed
            // without unregistering would otherwise be rung instead of the
            // machine the agent is actually sitting at.
            f.insert("max_contacts", "1".into());
            f.insert("remove_existing", "yes".into());
            // Minutes, not hours. A registration outliving the app is an agent
            // Asterisk believes is available and who is not there — the caller
            // hears ringing and nobody answers.
            f.insert("maximum_expiration", "300".into());
            f.insert("minimum_expiration", "60".into());
            f.insert("qualify_frequency", "30".into());
        }
    }
    line(&f)
}

/// An agent of this organisation who is on duty, if there is one.
///
/// **This is where tenant isolation actually lives.** The endpoint *name*
/// carries the org so that two clinics can both have a 4001, but a name is a
/// convention — nothing stops a caller's escalation naming somebody else's
/// extension. Filtering by `org_id` here does: the switch is the thing that
/// already knows which organisation a call belongs to, so it is the right place
/// to decide who may take it.
///
/// Deliberately not done with dialplan contexts. A context would be a second
/// copy of the same rule, in a file, able to disagree with this one.
///
/// Returns `None` when nobody is on duty, which the caller must treat as a real
/// answer: an escalation to an agent who is not registered is a caller
/// listening to ringing that nobody will answer.
pub async fn on_duty(
    base: &str,
    key: &str,
    org_id: &str,
) -> Option<String> {
    let rows = super::graph::rows(
        base,
        key,
        "agent_extensions",
        &[
            ("select", "endpoint".into()),
            ("org_id", format!("eq.{org_id}")),
            ("status", "eq.active".into()),
            // Oldest first, so the same agent is tried first every time rather
            // than whichever the database felt like returning. A fair rotation
            // is a queue, and a queue needs to know who is already on a call —
            // that belongs with the switch, not here.
            ("order", "created_at.asc".into()),
            ("limit", "1".into()),
        ],
    )
    .await
    .ok()?;

    rows.first()
        .and_then(|r| r.get("endpoint"))
        .and_then(Value::as_str)
        .map(|e| format!("PJSIP/{e}"))
}

/// The endpoint name Asterisk is asking about, out of its POST body.
///
/// It sends `id=<name>` for a single lookup and something like
/// `id LIKE=%` for a multi. Anything that is not a plain `id=` is treated as
/// "give me everything", which is what `multi` means.
pub fn wanted_id(form: &BTreeMap<String, String>) -> Option<String> {
    form.get("id").filter(|v| !v.is_empty() && *v != "%").cloned()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn agent() -> Agent {
        Agent {
            endpoint: "sarvathra-4001".into(),
            sip_password: "s3cret".into(),
            display_name: "Priya Nair".into(),
            extension: "4001".into(),
        }
    }

    fn fields(rendered: &str) -> BTreeMap<String, String> {
        rendered
            .split('&')
            .filter_map(|pair| pair.split_once('='))
            .map(|(k, v)| (k.to_string(), v.to_string()))
            .collect()
    }

    #[test]
    fn an_endpoint_names_its_auth_and_aor() {
        // All three objects share the endpoint's name. If they drift, Asterisk
        // finds an endpoint that authenticates against nothing and is
        // permanently Unavailable, with no error to read.
        let f = fields(&render(&agent(), Family::Endpoint));
        assert_eq!(f["id"], "sarvathra-4001");
        assert_eq!(f["auth"], "sarvathra-4001");
        assert_eq!(f["aors"], "sarvathra-4001");
        assert_eq!(f["webrtc"], "yes");
        assert_eq!(f["context"], "agents");
    }

    #[test]
    fn a_display_name_cannot_split_the_response() {
        // Asterisk parses this as a query string. A space or an ampersand left
        // raw turns one field into two, and the endpoint comes back subtly
        // wrong rather than missing.
        let rendered = render(&agent(), Family::Endpoint);
        assert!(!rendered.contains(' '), "{rendered}");
        let f = fields(&rendered);
        assert_eq!(f["callerid"], "Priya%20Nair%20%3C4001%3E");
    }

    #[test]
    fn an_ampersand_in_a_name_is_encoded() {
        let mut a = agent();
        a.display_name = "Rao & Co".into();
        let f = fields(&render(&a, Family::Endpoint));
        assert!(!f["callerid"].contains('&'), "{:?}", f["callerid"]);
        assert_eq!(f.get("Co"), None, "the name must not become its own field");
    }

    #[test]
    fn an_agent_with_no_name_still_has_a_caller_id() {
        let mut a = agent();
        a.display_name = String::new();
        let f = fields(&render(&a, Family::Endpoint));
        assert_eq!(f["callerid"], "Agent%20%3C4001%3E");
    }

    #[test]
    fn the_auth_carries_the_password_and_the_endpoint_does_not() {
        // A password in the endpoint object would be sent for every lookup
        // Asterisk makes, including ones that have nothing to do with signing in.
        let auth = fields(&render(&agent(), Family::Auth));
        assert_eq!(auth["password"], "s3cret");
        assert_eq!(auth["auth_type"], "userpass");
        assert!(!render(&agent(), Family::Endpoint).contains("s3cret"));
    }

    #[test]
    fn an_aor_expires_in_minutes() {
        let f = fields(&render(&agent(), Family::Aor));
        assert_eq!(f["max_contacts"], "1");
        assert_eq!(f["remove_existing"], "yes");
        assert_eq!(f["maximum_expiration"], "300");
    }

    #[test]
    fn only_the_three_families_are_served() {
        assert_eq!(Family::parse("ps_endpoints"), Some(Family::Endpoint));
        assert_eq!(Family::parse("ps_auths"), Some(Family::Auth));
        assert_eq!(Family::parse("ps_aors"), Some(Family::Aor));
        // Contacts are written by Asterisk on every registration; serving them
        // would mean implementing store/update/destroy for something that
        // expires in five minutes.
        assert_eq!(Family::parse("ps_contacts"), None);
        assert_eq!(Family::parse("anything_else"), None);
    }

    #[test]
    fn a_multi_lookup_asks_for_everything() {
        let single: BTreeMap<String, String> =
            [("id".to_string(), "sarvathra-4001".to_string())].into();
        assert_eq!(wanted_id(&single).as_deref(), Some("sarvathra-4001"));

        let multi: BTreeMap<String, String> = [("id".to_string(), "%".to_string())].into();
        assert_eq!(wanted_id(&multi), None, "% means give me all of them");

        let like: BTreeMap<String, String> =
            [("id LIKE".to_string(), "%".to_string())].into();
        assert_eq!(wanted_id(&like), None);
    }
}
