-- An agent is a person with an extension.
--
-- Tied to auth.users on purpose. Signing into the console — or, later, a phone
-- — is what gets you your SIP credentials, so "who took this call" is a real
-- identity rather than a shared handset. It also means org membership already
-- governs access through the same RLS everything else uses, with nothing new to
-- get wrong.
--
-- ## Why this is not PJSIP Realtime in the usual sense
--
-- Asterisk cannot read this database. It has no `res_config_pgsql` and no
-- `res_config_odbc` — only curl, ldap and sqlite3 — and the Supabase container
-- publishes no port on the host. So Asterisk uses `res_config_curl` and asks
-- the *bridge*, which already reads Supabase through PostgREST. Provisioning an
-- agent stays an INSERT here; the bridge is the realtime backend.
--
-- ## Multitenancy
--
-- Asterisk has no tenant concept. The endpoint name is the only thing carrying
-- the org, so it is `<org slug>-<extension>` and generated rather than typed —
-- a convention that depends on somebody remembering it is a convention that
-- ends in a collision between two clinics' extension 4001.

create table if not exists agent_extensions (
    id           uuid primary key default gen_random_uuid(),
    org_id       uuid not null references organizations (id) on delete cascade,

    -- The person. Nullable only so an extension can be provisioned before its
    -- owner accepts an invitation; an extension with no user cannot sign in and
    -- therefore cannot register.
    user_id      uuid references auth.users (id) on delete set null,

    -- What a colleague would say out loud. Digits only: it appears in SIP
    -- headers, in Asterisk's CLI and on a caller's display.
    extension    text not null check (extension ~ '^[0-9]{3,6}$'),

    -- What Asterisk knows this endpoint as. Derived, never typed.
    endpoint     text not null unique,

    -- The SIP password. Stored as it must be: PJSIP's digest authentication
    -- needs the plaintext to compute a response, so this cannot be hashed the
    -- way a login password is. It is therefore treated as a credential in its
    -- own right — never returned to the browser except to the person it belongs
    -- to, rotatable, and no more privileged than the extension it unlocks.
    sip_password text not null,

    -- Shown to whoever is called, and on the agent's own screen.
    display_name text not null default '',

    -- `active` may take calls. `suspended` keeps the row, the history and the
    -- extension number while refusing registration — which is what you want
    -- when somebody leaves, because deleting an agent would orphan every call
    -- they handled.
    status       text not null default 'active'
                 check (status in ('active', 'suspended')),

    created_at   timestamptz not null default now(),
    updated_at   timestamptz not null default now(),

    -- One extension per org, and one extension per person within an org.
    unique (org_id, extension),
    unique (org_id, user_id)
);

comment on table agent_extensions is
    'A human agent: a Supabase auth user with a SIP extension on Asterisk.';
comment on column agent_extensions.endpoint is
    'PJSIP endpoint name, <org slug>-<extension>. Generated by trigger; Asterisk has no tenant concept so the name carries the org.';
comment on column agent_extensions.sip_password is
    'Plaintext because SIP digest auth requires it. Never hashable; treat as a credential.';

-- The endpoint name is derived from the org and the extension, on write.
--
-- A generated column cannot do this because the slug lives in another table, so
-- it is a trigger — and it runs on update as well as insert, because an
-- extension that is renumbered without its endpoint following would keep
-- answering under its old name.
create or replace function set_agent_endpoint()
returns trigger
language plpgsql
as $$
declare
    org_slug text;
begin
    select slug into org_slug from organizations where id = new.org_id;
    if org_slug is null then
        raise exception 'organization % has no slug', new.org_id;
    end if;
    new.endpoint := org_slug || '-' || new.extension;
    new.updated_at := now();
    return new;
end;
$$;

drop trigger if exists agent_extensions_endpoint on agent_extensions;
create trigger agent_extensions_endpoint
    before insert or update on agent_extensions
    for each row execute function set_agent_endpoint();

create index if not exists agent_extensions_org_idx on agent_extensions (org_id, status);
create index if not exists agent_extensions_user_idx on agent_extensions (user_id);

alter table agent_extensions enable row level security;

-- Members of the organisation may see who its agents are — a supervisor needs
-- the roster to know who is on duty.
create policy agent_extensions_read on agent_extensions
    for select to authenticated
    using (is_org_member(org_id));

create policy agent_extensions_write on agent_extensions
    for all to authenticated
    using (is_org_member(org_id))
    with check (is_org_member(org_id));

-- What a signed-in person may safely fetch about themselves.
--
-- **The password is deliberately absent from the roster and present here.** A
-- view over a table with RLS runs as its owner and bypasses that RLS unless
-- `security_invoker` is set — the fault this project already found in migration
-- 0056, where every organisation's costs were readable by any signed-in user.
-- Any view over a table with RLS needs that line.
create or replace view my_agent_extension
with (security_invoker = true)
as
select a.id,
       a.org_id,
       a.extension,
       a.endpoint,
       a.sip_password,
       a.display_name,
       a.status,
       o.slug as org_slug
  from agent_extensions a
  join organizations o on o.id = a.org_id
 where a.user_id = auth.uid()
   and a.status = 'active';

comment on view my_agent_extension is
    'The signed-in user''s own SIP credentials. security_invoker, so RLS still applies.';

grant select on my_agent_extension to authenticated;
